Repository researchstudio-sat/webofneeds, pull requests merged in 2019-03, with the labels that each got.

#2776 Refac post content general
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
  webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-general.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
Labels: testing

#2777 Refac move group administration
  webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
  webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration-header.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration-selection-item.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-menu.js
  webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
  webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_group-administration-header.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_group-administration-selection-item-line.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_group-administration.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
Labels: testing

#2783 Don't download blazegraph with every build
  webofneeds/won-docker/image/bigdata/Dockerfile
Labels: testing

#2789 Feat Reaction- & Enabled UseCases
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
  webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
  webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling-interest.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-offer.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-search.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-personal-transport-search.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rideshare-offer.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-taxi-offer.js
Labels: testing

#2786 Showing add/remove persona button only when reasonable.
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-persona.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
Labels: testing

#2787 Fixed elm need decoder to use derived data.
  webofneeds/won-owner-webapp/src/main/webapp/elm/Application.elm
Labels: testing

#2790 Not displaying export without verification.
  webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java
  webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js
  webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
  webofneeds/won-owner-webapp/src/main/webapp/elm/Settings.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Export.elm
Labels: testing

#2799 Fixed overlow caused by svg element.
  webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Styled.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/Icons.elm
Labels: testing

#2801 Fixed generic need type display.
  webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js
Labels: testing

#2802 Fixed npm vulnerabilities.
  webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
  webofneeds/won-owner-webapp/src/main/webapp/package.json
Labels: testing

#2808 Fixes #2805 close message details does not work
  webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
Labels: testing

#2827 Paypal-Bot functionality reduced.
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/paypal-payment-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/paypal-payment-viewer.js
  webofneeds/won-owner-webapp/src/main/webapp/config/details/payment.js
Labels: testing

#2803 Removed dependency that was not used
  webofneeds/pom.xml
  webofneeds/won-owner-webapp/pom.xml
Labels: testing

#2815 fix textfield focus color to be browser independent (fixes #1813)
  webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Labels: testing

#2837 Feat improve register errormessage
  webofneeds/won-core/src/main/java/won/protocol/util/LoggingUtils.java
  webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/SendMessageFromNodeReactionProcessor.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/serversideaction/EventTriggeredActionContainer.java
  webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java
  webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerWonMessageSenderJMSBased.java
Labels: testing

#2800 remove saving closed connuris in localstorage and use the correct state from the backend (Feat lds uris by connstate)
  webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java
  webofneeds/won-core/src/main/java/won/protocol/repository/NeedRepository.java
  webofneeds/won-core/src/main/java/won/protocol/service/LinkedDataService.java
  webofneeds/won-core/src/main/java/won/protocol/service/NeedInformationService.java
  webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
  webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java
  webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
  webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
  webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
  webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
  webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js
  webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Labels: testing

#2826 Feat change password backend
  webofneeds/won-core/src/main/java/won/cryptography/service/keystore/FileBasedKeyStoreService.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/ChangePasswordPojo.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/ResetPasswordPojo.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/events/OnPasswordChangedEvent.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/events/OnRecoveryKeyGeneratedEvent.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/listener/PasswordChangeEMailListener.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/listener/RecoveryKeyGeneratedEMailListener.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/validator/PasswordChangeValidator.java
  webofneeds/won-owner-webapp/src/main/java/won/owner/web/validator/ResetPasswordValidator.java
  webofneeds/won-owner-webapp/src/main/resources/mail-templates/password-changed.vm
  webofneeds/won-owner-webapp/src/main/resources/mail-templates/recovery-key-generated.vm
  webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml
  webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
  webofneeds/won-owner/src/main/java/won/owner/model/EmailVerificationToken.java
  webofneeds/won-owner/src/main/java/won/owner/model/KeyStoreIOException.java
  webofneeds/won-owner/src/main/java/won/owner/model/KeystoreHolder.java
  webofneeds/won-owner/src/main/java/won/owner/model/TokenPurpose.java
  webofneeds/won-owner/src/main/java/won/owner/model/User.java
  webofneeds/won-owner/src/main/java/won/owner/repository/UserRepository.java
  webofneeds/won-owner/src/main/java/won/owner/service/impl/IncorrectPasswordException.java
  webofneeds/won-owner/src/main/java/won/owner/service/impl/KeystorePasswordUtils.java
  webofneeds/won-owner/src/main/java/won/owner/service/impl/UserNotFoundException.java
  webofneeds/won-owner/src/main/java/won/owner/service/impl/UserService.java
  webofneeds/won-owner/src/main/resources/db/migration/V9_0__add_token_purpose.sql
  webofneeds/won-owner/src/main/resources/db/migration/V9_1__add_recoverable_keystore_password.sql
Labels: do not merge, testing

#2841 Feat store connection state and (own) facettype in redux-state onload #2823 (rebased)
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
  webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/process-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
  webofneeds/won-owner-webapp/src/main/webapp/app/selectors/connection-selectors.js
  webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
  webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_won-markdown.scss
Labels: testing

#2834 Feat agree tos private #2537
  webofneeds/won-owner-webapp/src/main/webapp/app/account-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
  webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/modal-dialog.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/publish-button.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
  webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/submit-button.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
  webofneeds/won-owner-webapp/src/main/webapp/app/process-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
  webofneeds/won-owner-webapp/src/main/webapp/app/selectors/view-selectors.js
  webofneeds/won-owner-webapp/src/main/webapp/skin/current/tos.html
  webofneeds/won-owner-webapp/src/main/webapp/style/_modal-dialog.scss
Labels: GDPR, UX, enhancement, testing

#2835 Add Persona only available if need has holdableFacet
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-persona.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
Labels: design issue, testing

#2847 Feat upgrade to tomcat 9
  documentation/build-with-eclipse.md
  webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml
  webofneeds/won-docker/image/owner/Dockerfile
  webofneeds/won-docker/image/owner/ssl/server.xml
  webofneeds/won-docker/image/wonnode/Dockerfile
  webofneeds/won-docker/image/wonnode/ssl/server.xml
  webofneeds/won-node/pom.xml
  webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
  webofneeds/won-owner-webapp/src/main/webapp/WEB-INF/web.xml
  webofneeds/won-utils/pom.xml
  webofneeds/won-utils/won-utils-tls/pom.xml
  webofneeds/won-utils/won-utils-tls/src/main/java/won/utils/tls/AcceptAllCertsTrustManager.java
Labels: testing

#2839 Fix find interests/plans UseCases #2774
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
  webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
  webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling-interest.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling-plan.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-lunch-interest.js
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-lunch-plan.js
Labels: UX, enhancement, testing

#2844 Feat invite to group #2690
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-participants.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
  webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-participants.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
Labels: testing

#2846 Fixes #2677
  webofneeds/won-owner-webapp/src/main/webapp/app/components/footer.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_footer.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
  webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
Labels: testing

#2851 Update elm settings
  webofneeds/won-owner-webapp/src/main/webapp/package.json
Labels: testing

#2845 Remove or replace attribute id's in pickers
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/datetime-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
Labels: testing

#2849 Adapted UseCase Search
  webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
  webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js
  webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
Labels: testing
