Repository researchstudio-sat/webofneeds, pull requests merged in 2019-10, with the labels that each got.

#3087 Update elm to 0.19.1
  webofneeds/pom.xml
  webofneeds/won-owner-webapp/pom.xml
  webofneeds/won-owner-webapp/src/main/webapp/elm.json
  webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
  webofneeds/won-owner-webapp/src/main/webapp/package.json
  webofneeds/won-owner-webapp/src/main/webapp/patches/parcel-bundler+1.12.3.patch
Labels: Elm, do not merge

#3096 Fix account settings #3054
  webofneeds/won-owner-webapp/src/main/webapp/app/components/elm-react.jsx
  webofneeds/won-owner-webapp/src/main/webapp/app/components/settings-wrapper.js
  webofneeds/won-owner-webapp/src/main/webapp/app/components/settings-wrapper.jsx
  webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/settings.jsx
  webofneeds/won-owner-webapp/src/main/webapp/elm/AddPersona.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/Old/Persona.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/PublishButton.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/Settings.elm
  webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
  webofneeds/won-owner-webapp/src/main/webapp/style/_publish-button.scss
Labels: bug

#3100 Feat persona chat
  webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.jsx
  webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-persona.js
Labels: enhancement
